language: python
python:
  - "2.6"
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_calendar
  - KOTTI_TEST_DB_STRING=mysql+oursql://root@localhost:3306/kotti_calendar
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - pip install "pip==1.3.1"  # fix issue with fanstatic==1.0a
  - pip install psycopg2 oursql
  - pip install -e . -r https://raw.github.com/Kotti/Kotti/0.10b1/requirements.txt
  - pip install "Kotti==0.10b1"
  - pip install "wsgi_intercept==0.5.1"
  - python setup.py dev
before_script:
  - psql -c 'create database kotti_calendar;' -U postgres
  - mysql -e 'create database kotti_calendar;'
script: py.test --tb=native --cov=kotti_calendar --cov-report=term-missing
notifications:
  irc: "irc.freenode.org#kotti"
  email: false
